import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import ts from 'typescript';
const source = readFileSync(new URL('../src/recommendationLogic.ts', import.meta.url), 'utf8');
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const backendSource = readFileSync(new URL('../src-tauri/src/lib.rs', import.meta.url), 'utf8');
const code = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020 } }).outputText;
const { rankValue, dailySoloLp, historyLabels, availablePaths, choosePath, componentCredit } = await import(`data:text/javascript;base64,${Buffer.from(code).toString('base64')}`);
let checks = 0;
function test(name, fn) { fn(); checks++; console.log(`PASS ${name}`); }
const now = Date.now(), start = now - 12*3600000;
const match = { game_id:1, queue_id:420, timestamp:start+600000, duration_secs:1800, champion_id:110, win:true, kills:10, deaths:2, assists:10, cs:270, vision_score:40, gold_earned:15000, total_damage:30000, position:'BOTTOM' };
const sample = { timestamp:start, tier:'BRONZE',rank:'IV',lp:55,queue_type:'RANKED_SOLO_5x5',wins:10,losses:10 };
test('unknown rank cannot create the screenshot -745 LP',()=>assert.ok(Number.isNaN(rankValue('NONE','',0))));
test('apex tier changes do not add artificial LP',()=>assert.equal(rankValue('GRANDMASTER','I',500),rankValue('MASTER','I',500)));
test('division promotion is continuous',()=>assert.equal(rankValue('SILVER','IV',10)-rankValue('BRONZE','I',90),20));
test('daily LP requires a verified baseline',()=>assert.equal(dailySoloLp([{...sample,queue_type:''},{...sample,timestamp:now,lp:80,wins:11}],[match],start),null));
test('same-day covered Solo game reports actual delta',()=>assert.equal(dailySoloLp([sample,{...sample,timestamp:now,lp:80,wins:11}],[match],start),25));
test('account or sample mismatch is unavailable',()=>assert.equal(dailySoloLp([sample,{...sample,timestamp:now,lp:80,wins:25}],[match],start),null));
test('Flex cannot contaminate Solo LP',()=>assert.equal(dailySoloLp([sample,{...sample,timestamp:now,lp:80,wins:11}],[{...match,queue_id:440}],start),null));
test('missing earliest match blocks false daily net',()=>assert.equal(dailySoloLp([{...sample,timestamp:match.timestamp+1},{...sample,timestamp:now,lp:80,wins:11}],[match],start),null));
const games=Array.from({length:10},(_,i)=>({...match,game_id:i+1,timestamp:now-i*3600000-3600000}));
test('farmer history earns CS God',()=>assert.ok(historyLabels(games,now).some(l=>l.label==='CS GOD')));
test('custom games never earn labels',()=>assert.equal(historyLabels(games.map(g=>({...g,queue_id:0})),now).length,0));
test('small sample never earns history labels',()=>assert.equal(historyLabels(games.slice(0,4),now).length,0));
test('support farming is not judged against carry CS',()=>assert.ok(!historyLabels(games.map(g=>({...g,position:'UTILITY'})),now).some(l=>l.label==='CS GOD')));
const item = id => ({gold: id===1?400:3000, purchasable:true,from:[],into:[],stats:{abilityPower:id===3115?100:0,attackDamage:id===3153?40:0,lethality:0}});
const paths = availablePaths(110,[3153,3124,3085],[3006],[],item);
test('Varus has explicit AP and AD choices',()=>assert.ok(paths.some(p=>p.id==='varus-ap')&&paths.some(p=>p.id==='varus-onhit')));
test('completed Nashor adapts to AP',()=>assert.equal(choosePath(paths,'auto',[3115],item).id,'varus-ap'));
test('ambiguous Rageblade does not force a switch',()=>assert.equal(choosePath(paths,'auto',[3124],item).id,'recommended'));
test('defensive Zhonya does not force AP',()=>assert.equal(choosePath(paths,'auto',[3157],item).id,'recommended'));
test('manual AD lock survives AP purchase',()=>assert.equal(choosePath(paths,'varus-onhit',[3115],item).id,'varus-onhit'));
test('component does not trigger a new path',()=>assert.equal(choosePath(paths,'auto',[1],item).id,'recommended'));
const tree = id=>({...item(id),gold:id===10?1000:id===2?600:400,from:id===10?[2,1]:id===2?[1]:[]});
test('one component is not counted twice',()=>assert.equal(componentCredit(10,[1],tree),400));
test('duplicate owned components are counted correctly',()=>assert.equal(componentCredit(10,[1,1],tree),800));
test('TAB item path renders before the player roster',()=>assert.ok(appSource.indexOf('className="ov-build ov-build-primary"') < appSource.indexOf('className="ov-lanes"')));
test('TAB overlay has no duplicate full player-label drawer',()=>assert.ok(!appSource.includes('className="overlay-player-labels"')));
test('TAB overlay keeps its configured compact window size',()=>assert.ok(!backendSource.includes('520.0 * preference')));
console.log(`${checks} checks passed.`);
